# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d7f3bf0c14e84d1ece86557678a96d69728113faebf1c5bcc1127475dd969f43a0abdd5be1986350ab8f4edfc6f887c0bc63567d9901a92472bfca77a93666e

test:
  secret_key_base: 3d3044a81d4b404c9e8d1cd4d7bbf7d2ec4618f145b9e7146f07ed8b063297da8c8e3f1b640a45eb8ea06a55f30e91dec1e2754588073d33180f9c23bcf78b4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
